#!/usr/bin/env node
// activation-engine/activate.mjs — read the persisted index and activate the FULL
// operating stack (rules + guidelines + coordination + memory + skills) that
// applies to a target folder/repo/workspace. Requires a prior `node scan.mjs`.
//
// Usage:
//   node activate.mjs                    # activate for the current folder (cwd)
//   node activate.mjs d:\code\myapp      # activate for a specific folder
//   node activate.mjs --instance <name>  # activate a curated instance (bundle)
//   node activate.mjs --default          # activate this repo's default instance
//   node activate.mjs --json             # machine output
//   node activate.mjs --list             # show the saved index summary (+ staleness)
//
// Exit: 0 ok · 2 no index (run scan) · 3 target missing · 4 no such instance · 5 no default.

import path from 'node:path'
import {
  INDEX_JSON, INDEX_MD, CMD_PREFIX, exists, read, isUnder, slugOf, rel,
  readInstance, listInstances, readState, writeState,
  resolveWorkspace, memoryFor, findSkill, classifyRef,
} from './lib/common.mjs'

const args = process.argv.slice(2)
const flag = (n) => args.includes(n)
const opt = (n) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : undefined }
const asJson = flag('--json')
const listMode = flag('--list') || flag('--status')
let instanceName = opt('--instance')
const useDefault = flag('--default')
const rawTarget = args.filter((a) => !a.startsWith('--') && a !== instanceName)[0] ?? process.cwd()

// ---- help (no index required) ----------------------------------------------
if (flag('--help') || flag('-h') || args[0] === 'help') {
  console.log(`activation-engine — command guide
============================================================
Scan your machine once, then load exactly the rules, skills, guidelines and
memory that apply to whatever folder you're in — and save reusable bundles
("instances") you can re-activate with one command.

EVERYDAY
  /activate                Bootstrap the current folder: list the rules, memory,
                           coordination files and skills that apply here, then run
                           the pre-flight gates. Use at the start of work in a repo.
  /activate-scan           (Re)build the machine index. Run once after install, and
                           again whenever you add or remove skills / rules.
  /activate-list           Show what the last scan found + how old it is. Use to
                           confirm the index is fresh (it warns at 7 days).
  /activate-instances      List your saved bundles. Use to see what you have.
  /activate-help           This guide.

INSTANCES  (a bundle = chosen skills + rules + guidelines for one purpose)
  /activate create <name> [--purpose "…"] [--skills a,b] [--rules p1,p2]
           [--guidelines "g1;g2"] [--roots r]
                           Make a bundle by hand (e.g. frontend, security-audit).
  /activate create <name> --from-active [--path <dir>]
                           Seed a bundle from what the current folder resolves to —
                           the fastest way to capture a working setup.
  /activate add <name>    --skills|--rules|--guidelines|--roots <vals>
  /activate remove <name> --skills|--rules|--guidelines|--roots <vals>
                           Edit a bundle's contents any time.
  /activate-<name>         Activate that bundle (one command per instance).
  /activate default <name> [--for <path> | --global]
  /activate --default      Set a per-repo (or global) default, then activate it.
  /activate export <name> [--out file]
  /activate import <file> [--name new]
                           Move a bundle between machines (portable JSON).
  /activate rename <name> <new>   |   /activate delete <name>
  /activate sync           Regenerate all slash commands (run once after install).

FLAGS (any command)
  --json     machine-readable output       --list   index summary (with activate)
  --default  this repo's default instance  --path   scope a create/activate to a dir

WHEN TO USE WHAT
  Fresh machine, or you added skills   ->  /activate-scan
  Starting work in a repo              ->  /activate
  You repeat the same setup often      ->  make an instance, then /activate-<name>
  Unsure what's indexed / how old      ->  /activate-list
  Forgot a command                     ->  /activate-help

FILES
  index      ~/.claude/activation-engine/index.json (+ index.md mirror)
  instances  ~/.claude/activation-engine/instances/<slug>.json
  commands   ~/.claude/commands/activate-*.md   (generated by sync)

Full docs: https://github.com/PlayQodeX/activation-engine`)
  process.exit(0)
}

if (!exists(INDEX_JSON)) {
  console.error('[activate] no index found. Run the scan first:')
  console.error(`           node "${path.join(path.dirname(new URL(import.meta.url).pathname), 'scan.mjs')}"  (or: /activate scan)`)
  process.exit(2)
}

const index = JSON.parse(read(INDEX_JSON))
const ageMs = Date.now() - Date.parse(index.scannedAt)
const ageDays = ageMs / 86400000
const staleness = ageDays >= 1 ? `${ageDays.toFixed(1)}d old` : `${(ageMs / 3600000).toFixed(1)}h old`

// ---- --list / --status ------------------------------------------------------
if (listMode) {
  if (asJson) { console.log(JSON.stringify({ ...index, staleness }, null, 2)); process.exit(0) }
  const L = []
  L.push('activation-engine — saved index')
  L.push('='.repeat(50))
  L.push(`scanned : ${index.scannedAt}  (${staleness})`)
  L.push(`host    : ${index.host} (${index.platform})`)
  L.push(`roots   : ${index.roots.map(rel).join(', ')}  (depth ${index.depth})`)
  L.push('')
  for (const [k, v] of Object.entries(index.stats)) L.push(`  ${k.padEnd(20)} ${v}`)
  if (index.newSinceLastScan?.length) L.push(`\n  new since last scan: ${index.newSinceLastScan.join(', ')}`)
  L.push('')
  L.push(`Human mirror: ${rel(INDEX_MD)}`)
  if (ageDays >= 7) L.push(`\n⚠ index is ${staleness} — consider re-scanning (/activate scan).`)
  console.log(L.join('\n'))
  process.exit(0)
}

// ---- --default : resolve this repo's default instance -> instance mode ------
if (useDefault && !instanceName) {
  const { repoRoot } = resolveWorkspace(index, rawTarget)
  const st = readState()
  instanceName = st.defaults?.[slugOf(repoRoot)] || st.defaults?.['*']
  if (!instanceName) {
    console.error(`[activate] no default instance set for ${repoRoot}`)
    console.error('           set one: node instance.mjs default <name> [--for <path> | --global]')
    process.exit(5)
  }
}

// ---- --instance <name> : activate a curated bundle --------------------------
if (instanceName) {
  const inst = readInstance(instanceName)
  if (!inst) {
    console.error(`[activate] no such instance: ${instanceName}`)
    const all = listInstances()
    console.error(all.length ? `           available: ${all.map((i) => i.slug).join(', ')}` : '           (none yet — create one with instance.mjs create <name>)')
    process.exit(4)
  }
  const scope = opt('--path') ? path.resolve(opt('--path')) : (inst.roots?.[0] || process.cwd())
  const skills = (inst.skills || []).map((s) => ({ name: s, hit: findSkill(index, s) }))
  const rules = (inst.rules || []).map((r) => classifyRef(index, r))
  const guidelines = (inst.guidelines || []).map((g) => classifyRef(index, g))
  const mem = memoryFor(index, scope)
  const coord = (index.coordFiles || []).filter((c) => isUnder(scope, path.dirname(c.path)))

  const missingSkills = skills.filter((s) => !s.hit).map((s) => s.name)
  const untrusted = skills.filter((s) => s.hit && !s.hit.trusted).map((s) => s.name)
  const fresh = skills.filter((s) => s.hit && s.hit.isNew).map((s) => s.name)

  // record last-used instance (per-machine state)
  const st = readState(); st.last = inst.slug; st.lastAt = new Date().toISOString(); writeState(st)

  const out = {
    instance: inst.name, slug: inst.slug, purpose: inst.purpose || '',
    scope, staleness, skills, rules, guidelines, memory: mem?.path || null, coordFiles: coord,
    warnings: { missingSkills, untrusted, new: fresh },
  }
  if (asJson) { console.log(JSON.stringify(out, null, 2)); process.exit(0) }

  const I = []
  I.push(`ACTIVATE INSTANCE — ${inst.name}   (/${CMD_PREFIX}${inst.slug})`)
  I.push('='.repeat(60))
  if (inst.purpose) I.push(`purpose : ${inst.purpose}`)
  I.push(`scope   : ${scope}`)
  I.push(`index   : ${staleness}${ageDays >= 7 ? '  ⚠ stale — /activate scan' : ''}`)
  I.push('')
  I.push(`CURATED SKILLS (${skills.length}):`)
  for (const s of skills) {
    const tags = s.hit ? `[${s.hit.where}]${s.hit.trusted ? '' : ' ⚠untrusted'}${s.hit.isNew ? ' ✦new' : ''}` : '[MISSING]'
    I.push(`  - ${tags} ${s.name}${s.hit?.dir ? '  ' + rel(s.hit.dir) : ''}`)
  }
  if (!skills.length) I.push('  (none)')
  I.push('')
  I.push(`CURATED RULES (${rules.length}):`)
  for (const r of rules) I.push(`  - [${r.kind}] ${r.kind === 'literal' ? r.ref : rel(r.path)}`)
  if (!rules.length) I.push('  (none)')
  I.push('')
  I.push(`CURATED GUIDELINES (${guidelines.length}):`)
  for (const g of guidelines) I.push(`  - [${g.kind}] ${g.kind === 'literal' ? g.ref : rel(g.path)}`)
  if (!guidelines.length) I.push('  (none)')
  I.push('')
  I.push(`SCOPE MEMORY : ${mem ? rel(mem.path) : '(none matched)'}`)
  I.push(`COORDINATION : ${coord.length ? coord.map((c) => `[${c.kind}] ${rel(c.path)}`).join('  ') : '(none)'}`)
  if (missingSkills.length) I.push(`\n⚠ missing skills (not on this PC's index): ${missingSkills.join(', ')}`)
  if (untrusted.length) I.push(`⚠ untrusted skills (third-party/plugin — vet before use): ${untrusted.join(', ')}`)
  if (fresh.length) I.push(`✦ new since last scan (review): ${fresh.join(', ')}`)
  I.push('\nNext: load the listed rules/guidelines broad→narrow, apply the curated skills, run the mandatory pre-flight gates.')
  console.log(I.join('\n'))
  process.exit(0)
}

// ---- activate for a target --------------------------------------------------
const target = path.resolve(rawTarget)
if (!exists(target)) { console.error(`[activate] target does not exist: ${target}`); process.exit(3) }

const { repoRoot, ruleStack, coordFiles, memory, workspaceSkills } = resolveWorkspace(index, target)

// default-instance hint for this repo
const st = readState()
const defSlug = st.defaults?.[slugOf(repoRoot)] || st.defaults?.['*'] || null

const result = {
  target, repoRoot, scannedAt: index.scannedAt, staleness,
  ruleStack, coordFiles, memory: memory?.path || null,
  defaultInstance: defSlug,
  skills: {
    workspace: workspaceSkills,
    global: index.global?.skills || [],
    plugin: (index.global?.pluginSkills || []).map((s) => s.name),
    commands: index.global?.commands || [],
  },
}

if (asJson) { console.log(JSON.stringify(result, null, 2)); process.exit(0) }

// ---- human report -----------------------------------------------------------
const L = []
L.push('ACTIVATE — workspace bootstrap (from saved index)')
L.push('='.repeat(60))
L.push(`target    : ${target}`)
L.push(`repo root : ${repoRoot}`)
L.push(`index age : ${staleness}${ageDays >= 7 ? '  ⚠ stale — /activate scan' : ''}`)
if (defSlug) L.push(`default   : ${defSlug}   (activate with /${CMD_PREFIX}${defSlug} or --default)`)
L.push('')
L.push('RULE / GUIDELINE STACK  (read broad -> narrow; specific wins):')
for (const r of ruleStack) L.push(`  [${r.scope.padEnd(6)}] ${r.kind.padEnd(10)} ${rel(r.path)}`)
L.push(`  [memory] ${'MEMORY.md'.padEnd(10)} ${memory ? rel(memory.path) : '(none matched)'}`)
L.push('')
L.push('COORDINATION / STATE FILES:')
for (const c of coordFiles) L.push(`  - [${c.kind}] ${rel(c.path)}`)
if (!coordFiles.length) L.push('  (none)')
L.push('')
L.push(`WORKSPACE SKILLS reachable here (${workspaceSkills.length}):`)
for (const s of workspaceSkills) L.push(`  - ${s.name}  (${rel(s.dir)})`)
if (!workspaceSkills.length) L.push('  (none)')
L.push('')
L.push(`GLOBAL SKILLS (${result.skills.global.length}): ${result.skills.global.map((s) => s.name).join(', ')}`)
L.push('')
L.push(`PLUGIN SKILLS (${result.skills.plugin.length}, untrusted by default): ${result.skills.plugin.join(', ') || '(none)'}`)
if (result.skills.commands.length) L.push(`\nGLOBAL COMMANDS: ${result.skills.commands.join(', ')}`)
console.log(L.join('\n'))
