#!/usr/bin/env node
// activation-engine/instance.mjs — manage named, editable "instances": bundles of
// skills / rules / guidelines curated for a specific purpose. Every mutation
// re-generates one slash command per instance (~/.claude/commands/activate-<slug>.md)
// so the runnable command set always tracks the instances that exist.
//
// Verbs:
//   list
//   show   <name> [--json]
//   create <name> [--purpose "…"] [--skills a,b] [--rules p1,p2] [--guidelines "g1","g2"] [--roots r1,r2]
//   add    <name> [--skills a,b] [--rules p] [--guidelines "…"] [--roots r]
//   remove <name> [--skills a,b] [--rules p] [--guidelines "…"] [--roots r]
//   rename <name> <newName>
//   delete <name>
//   sync                      # regenerate all command files + prune orphans
//
// Instances persist in ~/.claude/activation-engine/instances/<slug>.json.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  INSTANCES_DIR, COMMANDS_DIR, CMD_PREFIX, CMD_MARKER,
  exists, read, kebab, listInstances, readInstance, writeInstance, deleteInstance, rel,
} from './lib/common.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ACTIVATE_MJS = path.join(HERE, 'activate.mjs')
const now = () => new Date().toISOString()

const argv = process.argv.slice(2)
const verb = argv[0]
const positionals = argv.slice(1).filter((a) => !a.startsWith('--'))
const opt = (name) => { const i = argv.indexOf(name); return i >= 0 ? argv[i + 1] : undefined }
const has = (name) => argv.includes(name)
const csv = (name) => (opt(name) || '').split(',').map((s) => s.trim()).filter(Boolean)
// guidelines may be quoted phrases w/ commas -> allow ; as the separator too
const csvSemi = (name) => (opt(name) || '').split(/[;,]/).map((s) => s.trim()).filter(Boolean)

function die(msg, code = 1) { console.error('[instance] ' + msg); process.exit(code) }

const FIELDS = ['skills', 'rules', 'guidelines', 'roots']
function collect(fromCreate = false) {
  return {
    skills: csv('--skills'),
    rules: csv('--rules'),
    guidelines: csvSemi('--guidelines'),
    roots: csv('--roots').map((r) => path.resolve(r)),
  }
}
const uniq = (a) => [...new Set(a)]

// ---- command-file generation ------------------------------------------------
function commandBody(inst) {
  const mjs = ACTIVATE_MJS.replace(/\\/g, '/')
  const purpose = inst.purpose ? ` — ${inst.purpose}` : ''
  return `---
description: "Activate activation-engine instance: ${inst.name}${purpose}"
---
<!-- ${CMD_MARKER} ; instance:${inst.slug} ; DO NOT EDIT (regenerated by instance.mjs) -->

Activate the **${inst.name}** instance from the \`activate\` (activation-engine) skill.

Run:

\`\`\`bash
node "${mjs}" --instance ${inst.slug}
\`\`\`

Then follow the **Activation procedure** in the \`activate\` skill for the stack it
prints: load the instance's rules/guidelines broad→narrow, surface its curated
skills, run the mandatory pre-flight gates, and report any items it flags missing.
`
}

function isGenerated(file) {
  return path.basename(file).startsWith(CMD_PREFIX) && read(file).includes(CMD_MARKER)
}

function syncCommands() {
  fs.mkdirSync(COMMANDS_DIR, { recursive: true })
  const instances = listInstances()
  const wanted = new Map(instances.map((i) => [CMD_PREFIX + i.slug + '.md', i]))
  // write/update
  for (const [fname, inst] of wanted) fs.writeFileSync(path.join(COMMANDS_DIR, fname), commandBody(inst))
  // prune orphaned generated commands
  let pruned = 0
  for (const f of fs.readdirSync(COMMANDS_DIR)) {
    if (!f.startsWith(CMD_PREFIX) || !f.endsWith('.md')) continue
    const full = path.join(COMMANDS_DIR, f)
    if (wanted.has(f)) continue
    if (isGenerated(full)) { fs.unlinkSync(full); pruned++ }
  }
  return { written: wanted.size, pruned }
}

function report(inst) {
  const c = (a) => (a && a.length ? a.length : 0)
  console.log(`  /${CMD_PREFIX}${inst.slug}   ${inst.name}${inst.purpose ? ' — ' + inst.purpose : ''}`)
  console.log(`     skills:${c(inst.skills)} rules:${c(inst.rules)} guidelines:${c(inst.guidelines)} roots:${c(inst.roots)}`)
}

// ---- verbs ------------------------------------------------------------------
switch (verb) {
  case 'list': {
    const items = listInstances()
    if (has('--json')) { console.log(JSON.stringify(items, null, 2)); break }
    console.log(`activation-engine — ${items.length} instance(s):`)
    if (!items.length) console.log('  (none — create one: instance create <name> …)')
    for (const i of items) report(i)
    break
  }

  case 'show': {
    const name = positionals[0] || die('show <name>')
    const inst = readInstance(name) || die(`no such instance: ${name}`, 2)
    if (has('--json')) { console.log(JSON.stringify(inst, null, 2)); break }
    console.log(`INSTANCE  ${inst.name}  (slug ${inst.slug})  ->  /${CMD_PREFIX}${inst.slug}`)
    if (inst.purpose) console.log(`purpose : ${inst.purpose}`)
    console.log(`created : ${inst.created}   updated: ${inst.updated}`)
    for (const f of FIELDS) {
      console.log(`${f.padEnd(11)}: ${(inst[f] && inst[f].length) ? '' : '(none)'}`)
      for (const v of inst[f] || []) console.log(`   - ${v}`)
    }
    break
  }

  case 'create': {
    const name = positionals[0] || die('create <name> [--purpose …] [--skills …] …')
    const slug = kebab(name)
    if (!slug) die('name produced an empty slug; use letters/numbers')
    if (exists(path.join(INSTANCES_DIR, slug + '.json'))) die(`instance "${slug}" already exists (use add/remove)`, 2)
    const f = collect(true)
    const inst = {
      name, slug, purpose: opt('--purpose') || '',
      created: now(), updated: now(),
      skills: uniq(f.skills), rules: uniq(f.rules),
      guidelines: uniq(f.guidelines), roots: uniq(f.roots),
    }
    writeInstance(inst)
    const s = syncCommands()
    console.log(`[instance] created "${name}" -> /${CMD_PREFIX}${slug}`)
    report(inst)
    console.log(`[instance] commands synced (${s.written} written, ${s.pruned} pruned)`)
    break
  }

  case 'add':
  case 'remove': {
    const name = positionals[0] || die(`${verb} <name> [--skills …] [--rules …] [--guidelines …] [--roots …]`)
    const inst = readInstance(name) || die(`no such instance: ${name}`, 2)
    const f = collect()
    let changed = 0
    for (const key of FIELDS) {
      const incoming = f[key]
      if (!incoming.length) continue
      const cur = new Set(inst[key] || [])
      for (const v of incoming) {
        if (verb === 'add') { if (!cur.has(v)) { cur.add(v); changed++ } }
        else { if (cur.delete(v)) changed++ }
      }
      inst[key] = [...cur]
    }
    if (!changed) die('nothing changed — specify --skills/--rules/--guidelines/--roots values that apply', 0)
    inst.updated = now()
    writeInstance(inst)
    syncCommands()
    console.log(`[instance] ${verb}: "${inst.name}" updated (${changed} field-value change(s))`)
    report(inst)
    break
  }

  case 'rename': {
    const name = positionals[0] || die('rename <name> <newName>')
    const newName = positionals[1] || die('rename <name> <newName>')
    const inst = readInstance(name) || die(`no such instance: ${name}`, 2)
    const newSlug = kebab(newName)
    if (!newSlug) die('new name produced an empty slug')
    if (newSlug !== inst.slug && exists(path.join(INSTANCES_DIR, newSlug + '.json'))) die(`target "${newSlug}" already exists`, 2)
    const oldSlug = inst.slug
    inst.name = newName; inst.slug = newSlug; inst.updated = now()
    if (newSlug !== oldSlug) deleteInstance(oldSlug)
    writeInstance(inst)
    const s = syncCommands()
    console.log(`[instance] renamed "${name}" -> "${newName}" (/${CMD_PREFIX}${newSlug}); commands synced (pruned ${s.pruned})`)
    break
  }

  case 'delete': {
    const name = positionals[0] || die('delete <name>')
    const inst = readInstance(name) || die(`no such instance: ${name}`, 2)
    deleteInstance(inst.slug)
    const s = syncCommands()
    console.log(`[instance] deleted "${inst.name}"; /${CMD_PREFIX}${inst.slug} removed (pruned ${s.pruned})`)
    break
  }

  case 'sync': {
    const s = syncCommands()
    console.log(`[instance] synced ${s.written} command(s), pruned ${s.pruned} orphan(s) in ${rel(COMMANDS_DIR)}`)
    break
  }

  default:
    die(`unknown verb "${verb || ''}". Use: list | show | create | add | remove | rename | delete | sync`, 2)
}
