#!/usr/bin/env node
// activation-engine/instance.mjs — manage named, editable "instances": bundles of
// skills / rules / guidelines curated for a specific purpose. Every mutation
// re-generates one slash command per instance (~/.claude/commands/activate-<slug>.md)
// so the runnable command set always tracks the instances that exist.
//
// Verbs:
//   list   [--grep <term>] [--json]
//   show   <name> [--json]
//   create <name> [--purpose "…"] [--skills a,b] [--rules p1,p2] [--guidelines "g1;g2"] [--roots r1,r2]
//   create <name> --from-active [--path <dir>]   # seed from the active workspace stack
//   add    <name> [--skills a,b] [--rules p] [--guidelines "…"] [--roots r]
//   remove <name> [--skills a,b] [--rules p] [--guidelines "…"] [--roots r]
//   rename <name> <newName>
//   delete <name>
//   default <name> [--for <path> | --global]     # set default instance for a repo / globally
//   default --clear [--for <path> | --global]
//   export <name> [--out <file>]                 # portable JSON (home paths -> ~)
//   import <file> [--name <newName>] [--force]
//   sync                                         # regenerate all command files + prune orphans
//
// Instances persist in ~/.claude/activation-engine/instances/<slug>.json.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  INSTANCES_DIR, COMMANDS_DIR, CMD_PREFIX, CMD_MARKER, INDEX_JSON,
  exists, read, kebab, slugOf, listInstances, readInstance, writeInstance, deleteInstance, rel,
  readState, writeState, resolveWorkspace, collapseHome, expandHome,
} from './lib/common.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ACTIVATE_MJS = path.join(HERE, 'activate.mjs')
const now = () => new Date().toISOString()

const argv = process.argv.slice(2)
const verb = argv[0]
const positionals = argv.slice(1).filter((a) => !a.startsWith('--'))
const opt = (name) => { const i = argv.indexOf(name); return i >= 0 ? argv[i + 1] : undefined }
const has = (name) => argv.includes(name)
const csv = (name) => (opt(name) || '').split(',').map((s) => s.trim()).filter(Boolean)
// guidelines may be quoted phrases w/ commas -> allow ; as the separator too
const csvSemi = (name) => (opt(name) || '').split(/[;,]/).map((s) => s.trim()).filter(Boolean)

function die(msg, code = 1) { console.error('[instance] ' + msg); process.exit(code) }

const FIELDS = ['skills', 'rules', 'guidelines', 'roots']
function collect(fromCreate = false) {
  return {
    skills: csv('--skills'),
    rules: csv('--rules'),
    guidelines: csvSemi('--guidelines'),
    roots: csv('--roots').map((r) => path.resolve(r)),
  }
}
const uniq = (a) => [...new Set(a)]

// ---- command-file generation ------------------------------------------------
function commandBody(inst) {
  const mjs = ACTIVATE_MJS.replace(/\\/g, '/')
  const purpose = inst.purpose ? ` — ${inst.purpose}` : ''
  return `---
description: "Activate activation-engine instance: ${inst.name}${purpose}"
---
<!-- ${CMD_MARKER} ; instance:${inst.slug} ; DO NOT EDIT (regenerated by instance.mjs) -->

Activate the **${inst.name}** instance from the \`activate\` (activation-engine) skill.

Run:

\`\`\`bash
node "${mjs}" --instance ${inst.slug}
\`\`\`

Then follow the **Activation procedure** in the \`activate\` skill for the stack it
prints: load the instance's rules/guidelines broad→narrow, surface its curated
skills, run the mandatory pre-flight gates, and report any items it flags missing.
`
}

function isGenerated(file) {
  return path.basename(file).startsWith(CMD_PREFIX) && read(file).includes(CMD_MARKER)
}

function syncCommands() {
  fs.mkdirSync(COMMANDS_DIR, { recursive: true })
  const instances = listInstances()
  const wanted = new Map(instances.map((i) => [CMD_PREFIX + i.slug + '.md', i]))
  // write/update
  for (const [fname, inst] of wanted) fs.writeFileSync(path.join(COMMANDS_DIR, fname), commandBody(inst))
  // prune orphaned generated commands
  let pruned = 0
  for (const f of fs.readdirSync(COMMANDS_DIR)) {
    if (!f.startsWith(CMD_PREFIX) || !f.endsWith('.md')) continue
    const full = path.join(COMMANDS_DIR, f)
    if (wanted.has(f)) continue
    if (isGenerated(full)) { fs.unlinkSync(full); pruned++ }
  }
  return { written: wanted.size, pruned }
}

function report(inst) {
  const c = (a) => (a && a.length ? a.length : 0)
  console.log(`  /${CMD_PREFIX}${inst.slug}   ${inst.name}${inst.purpose ? ' — ' + inst.purpose : ''}`)
  console.log(`     skills:${c(inst.skills)} rules:${c(inst.rules)} guidelines:${c(inst.guidelines)} roots:${c(inst.roots)}`)
}

// ---- verbs ------------------------------------------------------------------
switch (verb) {
  case 'list': {
    let items = listInstances()
    const g = opt('--grep')
    if (g) {
      const q = g.toLowerCase()
      items = items.filter((i) => (`${i.name} ${i.purpose || ''} ${[...(i.skills || []), ...(i.rules || []), ...(i.guidelines || [])].join(' ')}`).toLowerCase().includes(q))
    }
    if (has('--json')) { console.log(JSON.stringify(items, null, 2)); break }
    console.log(`activation-engine — ${items.length} instance(s)${g ? ` matching "${g}"` : ''}:`)
    if (!items.length) console.log(g ? '  (no matches)' : '  (none — create one: instance create <name> …)')
    for (const i of items) report(i)
    break
  }

  case 'show': {
    const name = positionals[0] || die('show <name>')
    const inst = readInstance(name) || die(`no such instance: ${name}`, 2)
    if (has('--json')) { console.log(JSON.stringify(inst, null, 2)); break }
    console.log(`INSTANCE  ${inst.name}  (slug ${inst.slug})  ->  /${CMD_PREFIX}${inst.slug}`)
    if (inst.purpose) console.log(`purpose : ${inst.purpose}`)
    console.log(`created : ${inst.created}   updated: ${inst.updated}`)
    for (const f of FIELDS) {
      console.log(`${f.padEnd(11)}: ${(inst[f] && inst[f].length) ? '' : '(none)'}`)
      for (const v of inst[f] || []) console.log(`   - ${v}`)
    }
    break
  }

  case 'create': {
    const name = positionals[0] || die('create <name> [--purpose …] [--skills …] …')
    const slug = kebab(name)
    if (!slug) die('name produced an empty slug; use letters/numbers')
    if (exists(path.join(INSTANCES_DIR, slug + '.json'))) die(`instance "${slug}" already exists (use add/remove)`, 2)
    const f = collect(true)
    // --from-active: seed from the operating stack the scan resolves for a folder
    const seed = { skills: [], rules: [], guidelines: [], roots: [] }
    if (has('--from-active')) {
      if (!exists(INDEX_JSON)) die('no index found — run the scan first (scan.mjs / /activate scan)', 2)
      const index = JSON.parse(read(INDEX_JSON))
      const at = opt('--path') ? path.resolve(opt('--path')) : process.cwd()
      const ws = resolveWorkspace(index, at)
      seed.skills = ws.workspaceSkills.map((s) => s.name)
      seed.rules = ws.ruleStack.filter((r) => r.scope !== 'global').map((r) => collapseHome(r.path)) // globals are always-on
      if (ws.memory) seed.guidelines = [collapseHome(ws.memory.path)]
      seed.roots = [ws.repoRoot]
      console.log(`[instance] --from-active seeded from ${ws.repoRoot}`)
    }
    const inst = {
      name, slug, purpose: opt('--purpose') || '',
      created: now(), updated: now(),
      skills: uniq([...seed.skills, ...f.skills]), rules: uniq([...seed.rules, ...f.rules]),
      guidelines: uniq([...seed.guidelines, ...f.guidelines]), roots: uniq([...seed.roots, ...f.roots]),
    }
    writeInstance(inst)
    const s = syncCommands()
    console.log(`[instance] created "${name}" -> /${CMD_PREFIX}${slug}`)
    report(inst)
    console.log(`[instance] commands synced (${s.written} written, ${s.pruned} pruned)`)
    break
  }

  case 'add':
  case 'remove': {
    const name = positionals[0] || die(`${verb} <name> [--skills …] [--rules …] [--guidelines …] [--roots …]`)
    const inst = readInstance(name) || die(`no such instance: ${name}`, 2)
    const f = collect()
    let changed = 0
    for (const key of FIELDS) {
      const incoming = f[key]
      if (!incoming.length) continue
      const cur = new Set(inst[key] || [])
      for (const v of incoming) {
        if (verb === 'add') { if (!cur.has(v)) { cur.add(v); changed++ } }
        else { if (cur.delete(v)) changed++ }
      }
      inst[key] = [...cur]
    }
    if (!changed) die('nothing changed — specify --skills/--rules/--guidelines/--roots values that apply', 0)
    inst.updated = now()
    writeInstance(inst)
    syncCommands()
    console.log(`[instance] ${verb}: "${inst.name}" updated (${changed} field-value change(s))`)
    report(inst)
    break
  }

  case 'rename': {
    const name = positionals[0] || die('rename <name> <newName>')
    const newName = positionals[1] || die('rename <name> <newName>')
    const inst = readInstance(name) || die(`no such instance: ${name}`, 2)
    const newSlug = kebab(newName)
    if (!newSlug) die('new name produced an empty slug')
    if (newSlug !== inst.slug && exists(path.join(INSTANCES_DIR, newSlug + '.json'))) die(`target "${newSlug}" already exists`, 2)
    const oldSlug = inst.slug
    inst.name = newName; inst.slug = newSlug; inst.updated = now()
    if (newSlug !== oldSlug) deleteInstance(oldSlug)
    writeInstance(inst)
    const s = syncCommands()
    console.log(`[instance] renamed "${name}" -> "${newName}" (/${CMD_PREFIX}${newSlug}); commands synced (pruned ${s.pruned})`)
    break
  }

  case 'delete': {
    const name = positionals[0] || die('delete <name>')
    const inst = readInstance(name) || die(`no such instance: ${name}`, 2)
    deleteInstance(inst.slug)
    const s = syncCommands()
    console.log(`[instance] deleted "${inst.name}"; /${CMD_PREFIX}${inst.slug} removed (pruned ${s.pruned})`)
    break
  }

  case 'default': {
    const st = readState(); st.defaults = st.defaults || {}
    // resolve the state key: global '*' or a repo root slug
    const keyFor = () => {
      if (has('--global')) return '*'
      const at = opt('--for') ? path.resolve(opt('--for')) : process.cwd()
      let root = at
      if (exists(INDEX_JSON)) { try { root = resolveWorkspace(JSON.parse(read(INDEX_JSON)), at).repoRoot } catch { /* keep at */ } }
      return slugOf(root)
    }
    if (has('--clear')) {
      const key = keyFor()
      if (st.defaults[key]) { delete st.defaults[key]; writeState(st); console.log(`[instance] cleared default for ${key === '*' ? '(global)' : key}`) }
      else console.log(`[instance] no default set for ${key === '*' ? '(global)' : key}`)
      break
    }
    const name = positionals[0] || die('default <name> [--for <path> | --global]  |  default --clear […]')
    const inst = readInstance(name) || die(`no such instance: ${name}`, 2)
    const key = keyFor()
    st.defaults[key] = inst.slug
    writeState(st)
    console.log(`[instance] default for ${key === '*' ? '(global)' : key} = ${inst.slug}  ->  activate with /${CMD_PREFIX}${inst.slug} or  activate --default`)
    break
  }

  case 'export': {
    const name = positionals[0] || die('export <name> [--out <file>]')
    const inst = readInstance(name) || die(`no such instance: ${name}`, 2)
    const portable = {
      schema: 'activation-engine/instance@1',
      name: inst.name, purpose: inst.purpose || '',
      skills: inst.skills || [],
      rules: (inst.rules || []).map(collapseHome),
      guidelines: (inst.guidelines || []).map(collapseHome),
      roots: (inst.roots || []).map(collapseHome),
    }
    const json = JSON.stringify(portable, null, 2)
    const outFile = opt('--out')
    if (outFile) { fs.writeFileSync(path.resolve(outFile), json); console.log(`[instance] exported "${inst.name}" -> ${path.resolve(outFile)}`) }
    else console.log(json)
    break
  }

  case 'import': {
    const file = positionals[0] || die('import <file.json> [--name <newName>] [--force]')
    const abs = path.resolve(file)
    if (!exists(abs)) die(`file not found: ${abs}`, 2)
    let data; try { data = JSON.parse(read(abs)) } catch { die('not valid JSON', 2) }
    const name = opt('--name') || data.name
    if (!name) die('import file has no "name" — pass --name <newName>', 2)
    const slug = kebab(name)
    if (!slug) die('name produced an empty slug')
    if (exists(path.join(INSTANCES_DIR, slug + '.json')) && !has('--force')) die(`instance "${slug}" already exists (use --name or --force)`, 2)
    const inst = {
      name, slug, purpose: data.purpose || '', created: now(), updated: now(),
      skills: uniq(data.skills || []),
      rules: uniq((data.rules || []).map(expandHome)),
      guidelines: uniq((data.guidelines || []).map(expandHome)),
      roots: uniq((data.roots || []).map(expandHome)),
    }
    writeInstance(inst)
    syncCommands()
    console.log(`[instance] imported -> "${name}" (/${CMD_PREFIX}${slug})`)
    report(inst)
    break
  }

  case 'sync': {
    const s = syncCommands()
    console.log(`[instance] synced ${s.written} command(s), pruned ${s.pruned} orphan(s) in ${rel(COMMANDS_DIR)}`)
    break
  }

  default:
    die(`unknown verb "${verb || ''}". Use: list | show | create | add | remove | rename | delete | default | export | import | sync`, 2)
}
