// activation-engine/lib/common.mjs
// Shared, zero-dependency helpers (node: builtins only). Read-only filesystem.
import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'

export const HOME = os.homedir()
export const GLOBAL_CLAUDE = path.join(HOME, '.claude')

// Canonical command guide. Single source shared by `activate.mjs --help` (CLI)
// and the generated `/activate-help` command (embedded verbatim — no LLM, no run).
export const HELP_TEXT = `activation-engine — command guide
============================================================
Scan your machine once, then load exactly the rules, skills, guidelines and
memory that apply to whatever folder you're in — and save reusable bundles
("instances") you can re-activate with one command.

EVERYDAY
  /activate                Bootstrap the current folder: list the rules, memory,
                           coordination files and skills that apply here, then run
                           the pre-flight gates. Use at the start of work in a repo.
  /activate-scan           (Re)build the machine index. Run once after install, and
                           again whenever you add or remove skills / rules.
  /activate-list           Show what the last scan found + how old it is. Use to
                           confirm the index is fresh (it warns at 7 days).
  /activate-instances      List your saved bundles. Use to see what you have.
  /activate-help           This guide.

INSTANCES  (a bundle = chosen skills + rules + guidelines for one purpose)
  /activate create <name> [--purpose "..."] [--skills a,b] [--rules p1,p2]
           [--guidelines "g1;g2"] [--roots r]
                           Make a bundle by hand (e.g. frontend, security-audit).
  /activate create <name> --from-active [--path <dir>]
                           Seed a bundle from what the current folder resolves to —
                           the fastest way to capture a working setup.
  /activate add <name>    --skills|--rules|--guidelines|--roots <vals>
  /activate remove <name> --skills|--rules|--guidelines|--roots <vals>
                           Edit a bundle's contents any time.
  /activate-<name>         Activate that bundle (one command per instance).
  /activate default <name> [--for <path> | --global]
  /activate --default      Set a per-repo (or global) default, then activate it.
  /activate export <name> [--out file]
  /activate import <file> [--name new]
                           Move a bundle between machines (portable JSON).
  /activate rename <name> <new>   |   /activate delete <name>
  /activate sync           Regenerate all slash commands (run once after install).

FLAGS (any command)
  --json     machine-readable output       --list   index summary (with activate)
  --default  this repo's default instance  --path   scope a create/activate to a dir

WHEN TO USE WHAT
  Fresh machine, or you added skills   ->  /activate-scan
  Starting work in a repo              ->  /activate
  You repeat the same setup often      ->  make an instance, then /activate-<name>
  Unsure what's indexed / how old      ->  /activate-list
  Forgot a command                     ->  /activate-help

FILES
  index      ~/.claude/activation-engine/index.json (+ index.md mirror)
  instances  ~/.claude/activation-engine/instances/<slug>.json
  commands   ~/.claude/commands/activate-*.md   (generated by sync)

Full docs: https://github.com/PlayQodeX/activation-engine`
// Where the persisted scan index lives (survives skill re-clone / update).
export const STATE_DIR = path.join(GLOBAL_CLAUDE, 'activation-engine')
export const INDEX_JSON = path.join(STATE_DIR, 'index.json')
export const INDEX_MD = path.join(STATE_DIR, 'index.md')
// Instances = named, editable bundles of skills/rules/guidelines.
export const INSTANCES_DIR = path.join(STATE_DIR, 'instances')
// Generated slash commands (one per instance) live here.
export const COMMANDS_DIR = path.join(GLOBAL_CLAUDE, 'commands')
export const CMD_PREFIX = 'activate-'
export const CMD_MARKER = 'generated-by: activation-engine'

// Normalise a display name to a filesystem/command-safe slug.
export const kebab = (s) => String(s).trim().toLowerCase()
  .replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')

export const instancePath = (slug) => path.join(INSTANCES_DIR, kebab(slug) + '.json')

export function listInstances() {
  if (!isDir(INSTANCES_DIR)) return []
  return fs.readdirSync(INSTANCES_DIR)
    .filter((f) => f.endsWith('.json'))
    .map((f) => { try { return JSON.parse(read(path.join(INSTANCES_DIR, f))) } catch { return null } })
    .filter(Boolean)
    .sort((a, b) => a.slug.localeCompare(b.slug))
}

// Resolve by slug OR case-insensitive display name.
export function readInstance(nameOrSlug) {
  const p = instancePath(nameOrSlug)
  if (exists(p)) { try { return JSON.parse(read(p)) } catch { return null } }
  const n = String(nameOrSlug).toLowerCase()
  return listInstances().find((i) => i.name.toLowerCase() === n || i.slug === kebab(nameOrSlug)) || null
}

export function writeInstance(inst) {
  fs.mkdirSync(INSTANCES_DIR, { recursive: true })
  fs.writeFileSync(instancePath(inst.slug), JSON.stringify(inst, null, 2))
}

export function deleteInstance(slug) {
  const p = instancePath(slug)
  if (exists(p)) { fs.unlinkSync(p); return true }
  return false
}

// ---- small per-machine state (default/last instance) ------------------------
export const STATE_JSON = path.join(STATE_DIR, 'state.json')
export function readState() { try { return JSON.parse(read(STATE_JSON)) } catch { return { defaults: {}, last: null } } }
export function writeState(s) { fs.mkdirSync(STATE_DIR, { recursive: true }); fs.writeFileSync(STATE_JSON, JSON.stringify(s, null, 2)) }

// ---- portable path helpers (for instance export/import) ---------------------
export const expandHome = (p) => (typeof p === 'string' && p.startsWith('~')) ? path.resolve(path.join(HOME, p.slice(1))) : p
export const collapseHome = (p) => {
  if (typeof p !== 'string') return p
  const abs = path.resolve(expandHome(p))
  return abs.startsWith(HOME) ? ('~' + abs.slice(HOME.length)).replace(/\\/g, '/') : abs
}

// ---- shared resolvers (used by activate.mjs AND instance.mjs) ---------------
export const ancestorsOf = (p) => {
  const out = []
  let cur = path.resolve(p)
  for (;;) { out.push(cur); const par = path.dirname(cur); if (par === cur) break; cur = par }
  return out
}

// nearest project memory for a folder (ancestor walk, case-insensitive slug)
export function memoryFor(index, dir) {
  for (const a of ancestorsOf(dir)) {
    const s = slugOf(a)
    const hit = (index.global?.memory || []).find((m) => m.project.toLowerCase() === s)
    if (hit) return hit
  }
  const base = path.basename(path.resolve(dir)).toLowerCase()
  return (index.global?.memory || [])
    .filter((m) => m.project.toLowerCase().includes(base))
    .sort((x, y) => y.project.length - x.project.length)[0] || null
}

// find an indexed skill (global | workspace | plugin) by name, case-insensitive.
// carries the `trusted` bit (global/workspace = trusted; plugin = trusted only if scan marked it so).
export function findSkill(index, name) {
  const n = String(name).toLowerCase()
  const g = (index.global?.skills || []).find((s) => s.name.toLowerCase() === n)
  if (g) return { name: g.name, where: 'global', dir: g.dir, trusted: g.trusted !== false, isNew: !!g.new }
  const w = (index.workspaceSkills || []).find((s) => s.name.toLowerCase() === n)
  if (w) return { name: w.name, where: 'workspace', dir: w.dir, trusted: w.trusted !== false, isNew: !!w.new }
  const p = (index.global?.pluginSkills || []).find((s) => s.name.toLowerCase() === n)
  if (p) return { name: p.name, where: 'plugin', dir: p.dir, trusted: p.trusted === true, isNew: !!p.new }
  return null
}

// classify a rule/guideline entry: existing file, memory-file slug, or literal text.
export function classifyRef(index, ref) {
  const abs = path.resolve(expandHome(ref))
  if (exists(abs)) return { ref, kind: 'file', path: abs }
  for (const m of index.global?.memory || []) {
    const cand = path.join(path.dirname(m.path), String(ref).endsWith('.md') ? ref : ref + '.md')
    if (exists(cand)) return { ref, kind: 'memory', path: cand }
  }
  return { ref, kind: 'literal' }
}

// resolve the operating stack that applies to a target folder from the index.
export function resolveWorkspace(index, targetIn) {
  const target = path.resolve(targetIn)
  const repoRoot = (index.gitRoots || [])
    .filter((r) => isUnder(target, r))
    .sort((a, b) => b.length - a.length)[0] || target
  const ruleStack = []
  if (index.global?.claudeMd) ruleStack.push({ scope: 'global', kind: 'CLAUDE.md', path: index.global.claudeMd })
  if (index.global?.rtkMd) ruleStack.push({ scope: 'global', kind: 'RTK.md', path: index.global.rtkMd })
  const anc = (index.ruleFiles || [])
    .filter((r) => isUnder(target, path.dirname(r.path)))
    .sort((a, b) => path.dirname(a.path).length - path.dirname(b.path).length)
  for (const r of anc) {
    const dir = path.dirname(r.path)
    ruleStack.push({ scope: samePath(dir, target) ? 'target' : (samePath(dir, repoRoot) ? 'repo' : 'app'), kind: r.kind, path: r.path })
  }
  const coordFiles = (index.coordFiles || []).filter((c) => isUnder(target, path.dirname(c.path)))
  const memory = memoryFor(index, target)
  const projectDirOf = (d) => d.split(/[\\/]\.claude[\\/]skills[\\/]/)[0]
  const workspaceSkills = (index.workspaceSkills || []).filter((s) => {
    const pd = projectDirOf(s.dir)
    return isUnder(target, pd) || isUnder(pd, repoRoot)
  })
  return { target, repoRoot, ruleStack, coordFiles, memory, workspaceSkills }
}

export const exists = (p) => { try { return fs.existsSync(p) } catch { return false } }
export const isDir = (p) => { try { return fs.statSync(p).isDirectory() } catch { return false } }
export const read = (p) => { try { return fs.readFileSync(p, 'utf8') } catch { return '' } }

// Dirs never worth walking into.
export const SKIP_DIRS = new Set([
  'node_modules', '.next', 'dist', 'build', '.git', 'coverage', '.turbo',
  '.vercel', 'out', '.cache', '.svelte-kit', 'vendor', 'target', '.venv',
  'venv', '__pycache__', '.gradle', '.idea', 'Pods', 'DerivedData',
  'worktrees', '.worktrees', 'AppData', 'Application Data',
])

// Portable "is `child` inside (or equal to) `parent`?"
// Windows paths are case-insensitive, and the drive letter's case varies by
// source (process.cwd() -> "d:\…" vs MSYS-converted args / scan -> "D:\…").
// Normalise case on win32 so comparisons don't spuriously fail.
const norm = (p) => (process.platform === 'win32' ? path.resolve(p).toLowerCase() : path.resolve(p))
export const samePath = (a, b) => norm(a) === norm(b)

export function isUnder(child, parent) {
  const c = norm(child)
  const p = norm(parent)
  if (c === p) return true
  return c.startsWith(p.endsWith(path.sep) ? p : p + path.sep)
}

// Per-cwd project slug, e.g. d:\claude-coding\atlas-labs -> d--claude-coding-atlas-labs
export const slugOf = (p) => path.resolve(p).replace(/[:\\/]/g, '-').toLowerCase()

// Cheap frontmatter (name + description) of a SKILL.md.
export function skillMeta(skillMd) {
  const txt = read(skillMd).slice(0, 4000)
  const fm = txt.match(/^---\s*([\s\S]*?)\s*---/)
  const block = fm ? fm[1] : txt
  const name = (block.match(/^name:\s*(.+)$/m)?.[1] || path.basename(path.dirname(skillMd))).trim()
  let desc = ''
  const dLine = block.match(/^description:\s*(.*)$/m)
  if (dLine) {
    if (/^[>|]/.test(dLine[1].trim()) || dLine[1].trim() === '') {
      const after = block.slice(block.indexOf(dLine[0]) + dLine[0].length)
      desc = after.split('\n').filter((l) => /^\s+\S/.test(l)).map((l) => l.trim()).join(' ')
    } else {
      desc = dLine[1].trim()
    }
  }
  return { name, description: desc.replace(/\s+/g, ' ').slice(0, 220) }
}

// List every <dir>/*/SKILL.md as {name, description, dir}.
export function listSkills(dir) {
  if (!isDir(dir)) return []
  const out = []
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!e.isDirectory()) continue
    const md = path.join(dir, e.name, 'SKILL.md')
    if (exists(md)) out.push({ dir: path.join(dir, e.name), ...skillMeta(md) })
  }
  return out.sort((a, b) => a.name.localeCompare(b.name))
}

// Bounded recursive walk. Calls onDir(fullPath, depth) for each directory.
export function walk(root, { depth = 6, onDir, budget = 200000 } = {}) {
  if (!isDir(root)) return
  const stack = [[path.resolve(root), 0]]
  let n = 0
  while (stack.length && n++ < budget) {
    const [cur, d] = stack.pop()
    if (onDir) onDir(cur, d)
    if (d >= depth) continue
    let entries = []
    try { entries = fs.readdirSync(cur, { withFileTypes: true }) } catch { continue }
    for (const e of entries) {
      if (!e.isDirectory()) continue
      if (SKIP_DIRS.has(e.name)) continue
      if (e.name.startsWith('.') && e.name !== '.claude') continue
      stack.push([path.join(cur, e.name), d + 1])
    }
  }
}

export const rel = (p) => (p && p.startsWith(HOME) ? '~' + p.slice(HOME.length) : p)

// ============================================================================
// Help document — one structured model rendered to Markdown + self-contained HTML.
// Deterministic (no LLM): `activate.mjs --help --write` regenerates both files.
// ============================================================================
export const DOC = {
  title: 'activation-engine',
  tagline: 'A Claude Code skill that loads the right rules and skills for the folder you are working in — automatically, before the first edit.',
  intro: [
    "Claude's instructions are scattered: a global `~/.claude/CLAUDE.md`, a `CLAUDE.md` per repo, per-app overlays, project memory, coordination files, and skills that live globally, in plugins, and inside individual repos. Every session, Claude has to rediscover which of those actually apply here.",
    'activation-engine indexes all of it once, then loads the exact subset that applies to your current folder — in one command. It also lets you save reusable **instances**: named bundles of skills + rules + guidelines, each with its own `/activate-<name>` command.',
  ],
  sections: [
    {
      id: 'install', h: 'Install',
      body: ['The skill is invoked as `/activate`, so it must live in a folder named `activate`. Clone it there, then generate its commands:'],
      code: { lang: 'bash', text: 'git clone https://github.com/PlayQodeX/activation-engine.git ~/.claude/skills/activate\nnode ~/.claude/skills/activate/instance.mjs sync   # registers the /activate-* commands' },
    },
    {
      id: 'everyday', h: 'Everyday commands',
      table: {
        cols: ['Command', 'What it does', 'When to use'],
        rows: [
          ['`/activate`', 'Loads the rules, memory, coordination files and skills that apply to the current folder, then runs the pre-flight checks.', 'At the start of work in any repo.'],
          ['`/activate-scan`', 'Rebuilds the machine index.', 'After install, and whenever you add/remove skills or rules.'],
          ['`/activate-list`', 'Shows what the last scan found and how old it is.', 'To check the index is fresh (warns at 7 days).'],
          ['`/activate-instances`', 'Lists your saved bundles.', 'To see what profiles you have.'],
          ['`/activate-help`', 'This guide, and (re)writes the Markdown + HTML reference.', 'When you forget a command.'],
        ],
      },
    },
    {
      id: 'instances', h: 'Instance commands',
      body: ['An instance is a saved bundle of skills + rules + guidelines for one purpose (e.g. `frontend`, `security-audit`). Each becomes its own `/activate-<name>` command.'],
      table: {
        cols: ['Command', 'What it does'],
        rows: [
          ['`/activate create <name> --from-active`', 'Make a bundle from what the current folder resolves to (fastest).'],
          ['`/activate create <name> --skills a,b --rules p --guidelines "g1;g2"`', 'Make a bundle by hand.'],
          ['`/activate add <name> --skills x` · `remove <name> --guidelines "…"`', "Edit a bundle's contents."],
          ['`/activate-<name>`', 'Activate that bundle (one command per instance).'],
          ['`/activate default <name>` then `/activate --default`', 'Set a per-repo default, then activate it in one flag.'],
          ['`/activate export <name>` · `import <file>`', 'Move a bundle between machines (portable JSON).'],
          ['`/activate rename <name> <new>` · `delete <name>`', 'Manage bundles.'],
        ],
      },
    },
    {
      id: 'flags', h: 'Flags (any command)',
      table: {
        cols: ['Flag', 'Meaning'],
        rows: [
          ['`--json`', 'Machine-readable output.'],
          ['`--list`', 'With `activate`: the saved-index summary.'],
          ['`--default`', "With `activate`: this repo's default instance."],
          ['`--path <dir>`', 'Scope a `create`/`activate` to a specific folder.'],
        ],
      },
    },
    {
      id: 'when', h: 'When to use what',
      list: [
        'Fresh machine, or you added skills → `/activate-scan`',
        'Starting work in a repo → `/activate`',
        'You repeat the same setup often → make an instance, then `/activate-<name>`',
        "Unsure what's indexed / how old → `/activate-list`",
        'Forgot a command → `/activate-help`',
      ],
    },
    {
      id: 'how', h: 'How activation works',
      body: [
        'Running `/activate` in a repo prints, in order: the **rule / guideline stack** (global `CLAUDE.md` + `RTK.md` → repo `CLAUDE.md` + `context.md` → app-level files → project `MEMORY.md`, sorted broad → narrow so the most specific layer wins); the **coordination / state files** (`active-tasks.md`, `blockers.md`, `known-bugs.md`); and the **skills reachable here**.',
        'Instance skills are checked against the index and tagged **MISSING** (not on this machine), **untrusted** (a third-party plugin skill), or **new** (added since the last scan), so a bundle stays honest as skills come and go.',
        'It degrades cleanly: a plain folder with no `CLAUDE.md`, memory or skills still produces a valid (smaller) result.',
      ],
    },
    {
      id: 'files', h: 'Where things live',
      code: { lang: 'text', text: '~/.claude/skills/activate/          the skill\n~/.claude/activation-engine/\n  index.json                       the machine index (regenerable)\n  index.md                         human-readable mirror\n  instances/<slug>.json            your saved bundles\n  activate-help.md / .html         this reference (generated by /activate-help)\n~/.claude/commands/activate-*.md   generated slash commands' },
    },
  ],
}

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
// inline: `code` and **bold** -> HTML (run after esc so tags are safe)
const inlineHtml = (s) => esc(s)
  .replace(/`([^`]+)`/g, '<code>$1</code>')
  .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')

export function renderMarkdown(doc = DOC) {
  const out = [`# ${doc.title}`, '', `> ${doc.tagline}`, '']
  for (const p of doc.intro) out.push(p, '')
  for (const s of doc.sections) {
    out.push(`## ${s.h}`, '')
    for (const p of s.body || []) out.push(p, '')
    if (s.table) {
      out.push(`| ${s.table.cols.join(' | ')} |`)
      out.push(`| ${s.table.cols.map(() => '---').join(' | ')} |`)
      for (const r of s.table.rows) out.push(`| ${r.map((c) => c.replace(/\|/g, '\\|')).join(' | ')} |`)
      out.push('')
    }
    if (s.list) { for (const li of s.list) out.push(`- ${li}`); out.push('') }
    if (s.code) out.push('```' + (s.code.lang || ''), s.code.text, '```', '')
  }
  out.push('---', '', `Full docs: <https://github.com/PlayQodeX/${doc.title}>`, '')
  return out.join('\n')
}

export function renderHtml(doc = DOC) {
  const nav = doc.sections.map((s) => `<a href="#${s.id}">${esc(s.h)}</a>`).join('')
  const body = doc.sections.map((s) => {
    let h = `<section id="${s.id}"><h2>${esc(s.h)}</h2>`
    for (const p of s.body || []) h += `<p>${inlineHtml(p)}</p>`
    if (s.table) {
      h += '<div class="tw"><table><thead><tr>' + s.table.cols.map((c) => `<th>${inlineHtml(c)}</th>`).join('') + '</tr></thead><tbody>'
      h += s.table.rows.map((r) => '<tr>' + r.map((c) => `<td>${inlineHtml(c)}</td>`).join('') + '</tr>').join('')
      h += '</tbody></table></div>'
    }
    if (s.list) h += '<ul>' + s.list.map((li) => `<li>${inlineHtml(li)}</li>`).join('') + '</ul>'
    if (s.code) h += `<pre><code>${esc(s.code.text)}</code></pre>`
    return h + '</section>'
  }).join('\n')
  const intro = doc.intro.map((p) => `<p>${inlineHtml(p)}</p>`).join('')
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(doc.title)} — command reference</title>
<style>
  :root{--bg:#0b0b12;--card:#14121f;--line:rgba(255,255,255,.08);--txt:#e8e6f0;--mut:#9a95b5;--acc:#a78bfa;--acc2:#7dd3fc;--code:#0f0e17}
  *{box-sizing:border-box}
  body{margin:0;background:var(--bg);color:var(--txt);font:16px/1.6 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;-webkit-font-smoothing:antialiased}
  .wrap{max-width:900px;margin:0 auto;padding:48px 24px 96px}
  header{border-bottom:1px solid var(--line);padding-bottom:28px;margin-bottom:32px}
  .eyebrow{color:var(--acc);font-weight:700;letter-spacing:.14em;font-size:12px;text-transform:uppercase}
  h1{font-size:44px;margin:.2em 0 .1em;letter-spacing:-.02em}
  .tag{color:var(--mut);font-size:18px;max-width:60ch}
  nav{display:flex;flex-wrap:wrap;gap:8px;margin:22px 0 0}
  nav a{color:var(--mut);text-decoration:none;font-size:13px;border:1px solid var(--line);border-radius:999px;padding:5px 12px}
  nav a:hover{color:var(--txt);border-color:var(--acc)}
  section{margin:36px 0}
  h2{font-size:22px;margin:0 0 14px;padding-top:8px;color:#fff}
  p{margin:0 0 14px;color:#d7d4e6}
  a{color:var(--acc2)}
  code{background:var(--code);border:1px solid var(--line);border-radius:5px;padding:.1em .4em;font:13.5px/1.5 "SFMono-Regular",Consolas,"Liberation Mono",monospace;color:#cfe8ff}
  pre{background:var(--code);border:1px solid var(--line);border-radius:10px;padding:16px 18px;overflow:auto}
  pre code{background:none;border:0;padding:0;color:#cdd6f4}
  .tw{overflow-x:auto;border:1px solid var(--line);border-radius:10px}
  table{border-collapse:collapse;width:100%;font-size:14.5px}
  th,td{text-align:left;padding:11px 14px;border-bottom:1px solid var(--line);vertical-align:top}
  th{background:rgba(167,139,250,.08);color:#fff;font-weight:600;white-space:nowrap}
  tr:last-child td{border-bottom:0}
  td code{white-space:nowrap}
  ul{margin:0 0 14px;padding-left:22px}li{margin:.25em 0;color:#d7d4e6}
  footer{margin-top:48px;padding-top:20px;border-top:1px solid var(--line);color:var(--mut);font-size:13px}
  @media(max-width:560px){h1{font-size:34px}.wrap{padding:32px 16px 64px}}
</style></head>
<body><div class="wrap">
<header>
  <div class="eyebrow">Claude Code skill</div>
  <h1>${esc(doc.title)}</h1>
  <div class="tag">${inlineHtml(doc.tagline)}</div>
  ${intro}
  <nav>${nav}</nav>
</header>
${body}
<footer>Generated by <code>/activate-help</code> · <a href="https://github.com/PlayQodeX/${esc(doc.title)}">github.com/PlayQodeX/${esc(doc.title)}</a></footer>
</div></body></html>
`
}

export function writeHelpDocs(dir = STATE_DIR) {
  fs.mkdirSync(dir, { recursive: true })
  const md = path.join(dir, 'activate-help.md')
  const html = path.join(dir, 'activate-help.html')
  fs.writeFileSync(md, renderMarkdown(DOC))
  fs.writeFileSync(html, renderHtml(DOC))
  return { md, html }
}
